print("What is your name human?")
name = input()
print("How old are you? (in years)")
age = int(input())
print("how tall are you (in meters")
height = float(input())
print("how much do you weigh? (in kilograms)")
weight = float(input())
bmi = weight / (height**2)
print(f"{name} you are {age} your bmi is {bmi}")